apiVersion: v1
kind: Service
metadata:
  name: pictures-web-service
  
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30010
  selector:
    app: pictures
    tier: web
          
      