# Default values for pictures-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameSpace: development
replicaCount: 2

image:
  repository: 785548451685.dkr.ecr.ap-south-1.amazonaws.com/homelabs
  tag: pictures-web
  ports: 
    - name: http
      containerPort: 3000
      protocol: tcp

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  type: LoadBalancer
  ports: 
    - name: web-port
      port: 80
      targetPort: 3000

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

ingress:
  enabled: false

