apiVersion: apps/v1
kind: Deployment

metadata:
  name: pictures-web-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: pictures
      tier: web
  template:
    spec:
      containers:
        - name: pictures-web
          image: aparihar/homelabs:pictures-web
          ports:
            - containerPort: 3000
          
    metadata:
      labels:
        app: pictures
        tier: web

---
apiVersion: v1
kind: Service
metadata:
  name: pictures-web-service
  
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 80
    targetPort: 3000
  selector:
    app: pictures
    tier: web
