apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-homelabs-pictures
  region: ap-south-1

nodeGroups:
  - name: ng-public
    instanceType: t2.small
    desiredCapacity: 3
    maxSize: 5
    ssh:
      publicKeyName: eks-homelabs-keypair
    availabilityZones: ["ap-south-1a", "ap-south-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: public-workload
      instance-type: onDemand

fargateProfiles:
  # - name: fp-default
  #   selectors:
  #     - namespace: kube-system

  - name: fp-development
    selectors: 
      - namespace: development
