apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictures-web-deployment
spec:
  template:
    spec:
      containers:
        - name: pictures-web
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
            
