kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: viewer-role-binding
subjects:
- kind: User
  name: eks-homelabs-viewer
  apiGroup: ""
roleRef:
  kind: Role
  name: viewer-role
  apiGroup: ""