apiVersion: v1
kind: Service
metadata:
  name: pictures-web-service
  annotations:
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
spec:
  type: LoadBalancer
  # ports:
  #   - port: 80
  #     targetPort: 3000
  # selector:
  #   app: pictures
  #   tier: web