apiVersion:  networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pictures-web-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=120
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: pictures-web-service
              servicePort: 80