apiVersion: v1
kind: Service
metadata:
  name: pictures-web-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: LoadBalancer
  # ports:
  #   - port: 80
  #     targetPort: 3000
  # selector:
  #   app: pictures
  #   tier: web