apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-calculator-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-calculator
      tier: backend
  template:
    spec:
      containers:
        - name: simple-calculator-service
          image: 785548451685.dkr.ecr.ap-south-1.amazonaws.com/todos:simple-calculator-microsvc
          ports:
            - containerPort: 9001
          
    metadata:
      labels:
        app: simple-calculator
        tier: backend

---

apiVersion: v1
kind: Service
metadata:
  name: simple-calculator-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
spec:
  type: LoadBalancer
  ports:
  - name: simple-calculator-service-port
    port: 80
    targetPort: 9001
  selector:
    app: simple-calculator
    tier: backend