Description: >-
  Custom CDKToolkit Stack.
  Use case : Use existing S3 bucket for CDK bootstraping
Parameters:
  StagingBucketName:
    Type: String
  StagingBucketRegion:
    Type: String
# used to report insights on cdk usage
Resources:
  CDKMetadata:
    Type: "AWS::CDK::Metadata"
    Properties:
      Modules: aws-cdk=1.87.1
Outputs:
  BucketName:
    Description: Name of the existing S3 bucket
    Value: !Ref StagingBucketName
  BucketDomainName:
    Description: Domain name of the existing S3 bucket
    Value:
      Fn::Sub:
        - ${Bucket}.${Region}.amazonaws.com
        - Bucket: !Ref StagingBucketName
          Region: !Ref StagingBucketRegion
