apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    mesh: development-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    
---

apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: development-mesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: development-mesh