apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-calculator-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-calculator
  template:
    spec:
      serviceAccountName: envoy-proxy-pod
      containers:
        - name: simple-calculator-service
          image: 785548451685.dkr.ecr.ap-south-1.amazonaws.com/todos:simple-calculator-microsvc
          ports:
            - containerPort: 9001
    metadata:
      labels:
        app: simple-calculator
        
---

apiVersion: v1
kind: Service
metadata:
  
  name: simple-calculator-service
spec:
  ports:
    - name: simple-calculator-service-port
      port: 9001
      targetPort: 9001
  selector:
    app: simple-calculator
    
---